# Generated by Django 5.1.2 on 2024-10-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_caracteristica', models.CharField(max_length=45, verbose_name='Característica')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_categoria', models.CharField(max_length=45, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomb_marca', models.CharField(max_length=45, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_caract', models.CharField(max_length=45, verbose_name='Descripción')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.caracteristica', verbose_name='Característica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagina.producto', verbose_name='Producto')),
            ],
        ),
    ]
