# Generated by Django 5.1.2 on 2024-10-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_alter_caracteristica_nomb_caracteristica_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productocaracteristica',
            unique_together={('producto', 'caracteristica')},
        ),
    ]
